[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.8.0"]

[tool.hatch.version]
path = "src/nhflotools/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = ["/.githooks", "/.github", "/.mypy_cache", "/.pytest_cache", "sonar-project.properties"]

[tool.hatch.build.targets.wheel]
packages = ["src/nhflotools"]

[tool.hatch.publish.index]
disable = true # Requires confirmation when publishing to pypi.

[project]
authors = [{ name = "Bas des Tombe", email = "bas.des.tombe@pwn.nl" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.11",
  "Topic :: Utilities",
]
dependencies = [
  "dask",
  "flopy",
  "geopandas",
  "matplotlib",
  "nlmod>=0.7.3b",
  "numpy",
  "pandas",
  "pykrige",
  "scipy",
  "seaborn",
  "shapely",
  "tqdm",
  "xarray",
]
description = "Tools that support the NHFLO modeling environment."
dynamic = ["version"]
keywords = ["NHFLO"]
license = { file = "LICENSE.txt" }
maintainers = [{ name = "Bas des Tombe", email = "bas.des.tombe@pwn.nl" }]
name = "nhflotools"
readme = "README.md"
requires-python = ">=3.9, <3.12"

[project.optional-dependencies]
dev = ["hatch", "pytest", "ruff"]

[tool.hatch.envs.default]
features = ["dev"]

[tool.hatch.envs.default.scripts]
fast-test = ["pytest ./tests/ -m \"not slow\""]
format = ["ruff check --fix .", "ruff format ."]
lint = ["ruff check ."]
test = ["pytest ./src/ ./tests/"]                # --doctest-modules

[tool.hatch.envs.matrix_test]
features = ["dev"]

[[tool.hatch.envs.matrix_test.matrix]]
python = ["3.10", "3.11", "3.9"]

[tool.hatch.envs.matrix_test.scripts]
test = ["pytest ./tests/"] # --doctest-modules

[tool.pytest.ini_options]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
testpaths = ["tests"]
