[build-system]
requires = ["hatchling>=1.8.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/nhflotools/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github", "/.mypy_cache", "/.pytest_cache", "/.githooks",
  "sonar-project.properties"
]

[tool.hatch.build.targets.wheel]
packages = ["src/nhflotools"]

[tool.hatch.publish.index]
disable = true  # Requires confirmation when publishing to pypi.

[project]
name = "nhflotools"
description = "Tools that support the NHFLO modeling environment."
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.9, <3.12"
authors = [
  {name = "Onno Ebbens", email = "o.ebbens@artesia-water.nl"},
  {name = "Davíd Brakenhoff", email = "d.brakenhoff@artesia-water.nl"},
  {name = "Bas des Tombe", email = "bas.des.tombe@pwn.nl"},
]
maintainers = [
  {name = "Onno Ebbens", email = "o.ebbens@artesia-water.nl"},
  {name = "Davíd Brakenhoff", email = "d.brakenhoff@artesia-water.nl"},
  {name = "Bas des Tombe", email = "bas.des.tombe@pwn.nl"},
]
keywords = [
  "NHFLO",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "geopandas",
    "xarray",
    "nlmod",
    "flopy",
    "seaborn",
    "shapely",
    "tqdm",
    "pykrige"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "hatch",
    "ruff",
    "isort",
    "black",
    "mypy",
    "types-PyYAML",     # for pyyaml types
    "types-requests",   # for requests types
    "types-xmltodict",  # for xmltodict types
    "pandas-stubs",     # for pandas types
    "pytest"
]

[tool.hatch.envs.default]
features = ["dev"]

[tool.hatch.envs.default.scripts]
lint = [
  "ruff check src/ tests/",
  "black --check src/ tests/",
  "isort --check-only --diff src/ tests/",
  "mypy src/",
]
format = ["black src/ tests/", "isort src/ tests/", "ruff check --fix src/ tests/", "ruff format src/ tests/", "lint",]
test = ["pytest ./src/ ./tests/",]  # --doctest-modules
fast-test = ["pytest ./tests/ -m \"not slow\"",]

[tool.hatch.envs.matrix_test]
features = ["dev"]

[[tool.hatch.envs.matrix_test.matrix]]
python = ["3.9", "3.10", "3.11"]

[tool.hatch.envs.matrix_test.scripts]
test = ["pytest ./tests/",]  # --doctest-modules

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.ruff]
extend-include = ["*.ipynb"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]



[tool.isort]
py_version=39
force_single_line = true
known_first_party = ["nhflotools"]
skip = [".gitignore", ".tox", ".venv"]
src_paths = ["src", "tests"]
line_length = 120

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
extend-exclude = ".venv"

[tool.mypy]
ignore_missing_imports = true  # Preferably false, but matplotlib, scipy and statsmodels are missing typing stubs
python_version = "3.9"